# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoter.proto\x12\x08ringvote\"\xc8\x01\n\x05Voter\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12.\n\x0b\x65xtra_infos\x18\x02 \x03(\x0b\x32\x19.ringvote.Voter.ExtraInfo\x12\x17\n\npublic_key\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x1aK\n\tExtraInfo\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ontent\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_titleB\n\n\x08_contentB\x07\n\x05_nameB\r\n\x0b_public_keyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VOTER']._serialized_start=26
  _globals['_VOTER']._serialized_end=226
  _globals['_VOTER_EXTRAINFO']._serialized_start=127
  _globals['_VOTER_EXTRAINFO']._serialized_end=202
# @@protoc_insertion_point(module_scope)
