# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ballot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61llot.proto\x12\x08ringvote\"A\n\x06\x42\x61llot\x12\x11\n\tresponses\x18\x01 \x03(\x05\x12\x16\n\tsignature\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x0c\n\n_signatureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ballot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BALLOT']._serialized_start=26
  _globals['_BALLOT']._serialized_end=91
# @@protoc_insertion_point(module_scope)
