# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: question.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equestion.proto\x12\x08ringvote\"s\n\x08Question\x12\x15\n\x08question\x18\x01 \x01(\tH\x00\x88\x01\x01\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x16.ringvote.QuestionTypeH\x01\x88\x01\x01\x12\x0f\n\x07\x63hoices\x18\x03 \x03(\tB\x0b\n\t_questionB\x07\n\x05_type*\xb6\x02\n\x0cQuestionType\x12\x1d\n\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15QUESTION_TYPE_INTEGER\x10\x01\x12\x19\n\x15QUESTION_TYPE_DECIMAL\x10\x02\x12\x18\n\x14QUESTION_TYPE_STRING\x10\x03\x12\x17\n\x13QUESTION_TYPE_BYTES\x10\x04\x12\x1f\n\x1bQUESTION_TYPE_SINGLE_CHOICE\x10\x05\x12+\n\'QUESTION_TYPE_SINGLE_CHOICE_ALLOW_OTHER\x10\x06\x12!\n\x1dQUESTION_TYPE_MULTIPLE_CHOICE\x10\x07\x12-\n)QUESTION_TYPE_MULTIPLE_CHOICE_ALLOW_OTHER\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QUESTIONTYPE']._serialized_start=146
  _globals['_QUESTIONTYPE']._serialized_end=456
  _globals['_QUESTION']._serialized_start=28
  _globals['_QUESTION']._serialized_end=143
# @@protoc_insertion_point(module_scope)
