# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import question_pb2 as question__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\x12\x08ringvote\x1a\x0equestion.proto\"\xe6\x01\n\x08Response\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x16.ringvote.QuestionTypeH\x00\x88\x01\x01\x12\x16\n\tint_field\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x19\n\x0c\x64ouble_field\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x19\n\x0cstring_field\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x62ytes_field\x18\x05 \x01(\x0cH\x04\x88\x01\x01\x42\x07\n\x05_typeB\x0c\n\n_int_fieldB\x0f\n\r_double_fieldB\x0f\n\r_string_fieldB\x0e\n\x0c_bytes_fieldb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESPONSE']._serialized_start=45
  _globals['_RESPONSE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
