# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import question_pb2 as question__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eresponse.proto\x12\x08ringvote\x1a\x0equestion.proto\"\xd7\x01\n\x08Response\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x16.ringvote.QuestionTypeH\x00\x88\x01\x01\x12(\n\x06\x66ields\x18\x02 \x03(\x0b\x32\x18.ringvote.Response.Field\x1am\n\x05\x46ield\x12\x13\n\tint_field\x18\x01 \x01(\x03H\x00\x12\x17\n\rdecimal_field\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_field\x18\x03 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_field\x18\x04 \x01(\x0cH\x00\x42\x07\n\x05\x66ieldB\x07\n\x05_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_RESPONSE']._serialized_start=45
  _globals['_RESPONSE']._serialized_end=260
  _globals['_RESPONSE_FIELD']._serialized_start=142
  _globals['_RESPONSE_FIELD']._serialized_end=251
# @@protoc_insertion_point(module_scope)
