# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoter.proto\x12\x08ringvote\"\xb1\x01\n\x05Voter\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x32\n\nextra_info\x18\x02 \x03(\x0b\x32\x1e.ringvote.Voter.ExtraInfoEntry\x12\x17\n\npublic_key\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x1a\x30\n\x0e\x45xtraInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05_nameB\r\n\x0b_public_keyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTER_EXTRAINFOENTRY._options = None
  _VOTER_EXTRAINFOENTRY._serialized_options = b'8\001'
  _globals['_VOTER']._serialized_start=26
  _globals['_VOTER']._serialized_end=203
  _globals['_VOTER_EXTRAINFOENTRY']._serialized_start=131
  _globals['_VOTER_EXTRAINFOENTRY']._serialized_end=179
# @@protoc_insertion_point(module_scope)
